"""
Minimal, dependency-free PDB writer for visualisation purposes.

CHAP writes an annotated ``output.pdb`` alongside its results, in which
per-residue pathway properties (e.g. radial distance from the
centreline, or pore-facing status) are stored in the B-factor
("temperature factor") column, so that molecular graphics programs like
VMD or PyMOL can colour the structure by that property with a plain
"colour by beta" representation -- see
https://www.channotation.org/docs/molecular_graphics_vmd/.

This module reimplements just enough of the PDB ``ATOM`` record format
to make that work, without depending on MDAnalysis (which is otherwise
needed for reading real trajectory files, but not for this purely
cosmetic, opt-in export step).
"""

from __future__ import annotations

import numpy as np


def write_minimal_pdb(
    positions: np.ndarray,
    resnames,
    resids,
    atom_names,
    path,
    b_factors=None,
    occupancies=None,
    elements=None,
    chain: str = "A",
    title: str = "pychap annotated structure",
):
    """Write a minimal but valid PDB file with ATOM records.

    Parameters
    ----------
    positions:
        ``(N, 3)`` array of atom coordinates, in Angstrom.
    resnames, resids, atom_names:
        Length-``N`` sequences of per-atom residue name, residue id, and
        atom name.
    path:
        Output file path.
    b_factors:
        Optional length-``N`` sequence of per-atom B-factor values (e.g.
        a continuous pathway property such as hydrophobicity or radial
        distance, broadcast from residue to atom level). If omitted, all
        B-factors are written as 0.00.
    occupancies:
        Optional length-``N`` sequence of per-atom occupancy values.
        Following a common structural-biology convention (and CHAP's own
        output), this is used here as a binary *flag* column -- e.g. 1.0
        for pore-facing atoms and 0.0 otherwise -- kept separate from the
        continuous ``b_factors`` property, so that molecular graphics
        software can select on one (``occupancy > 0.5``) while colouring
        by the other (``beta``). Defaults to 1.0 for every atom if omitted.
    elements:
        Optional length-``N`` sequence of element symbols (used for the
        columns 77-78 element field, which some viewers use to guess
        atom colours/radii if not otherwise specified). Guessed from the
        atom name if omitted.
    chain:
        Chain identifier written for every atom (PDB files need *some*
        chain ID; this writer doesn't attempt multi-chain topology).
    """
    positions = np.asarray(positions, dtype=float)
    n_atoms = len(positions)

    if len(resnames) != n_atoms or len(resids) != n_atoms or len(atom_names) != n_atoms:
        raise ValueError("resnames, resids, and atom_names must all have length N (one per atom)")

    if b_factors is None:
        b_factors = np.zeros(n_atoms)
    else:
        b_factors = np.asarray(b_factors, dtype=float)
        if len(b_factors) != n_atoms:
            raise ValueError("b_factors must have length N (one per atom)")

    if occupancies is None:
        occupancies = np.ones(n_atoms)
    else:
        occupancies = np.asarray(occupancies, dtype=float)
        if len(occupancies) != n_atoms:
            raise ValueError("occupancies must have length N (one per atom)")

    if elements is None:
        elements = [_guess_element(name) for name in atom_names]
    elif len(elements) != n_atoms:
        raise ValueError("elements must have length N (one per atom)")

    with open(path, "w") as fh:
        fh.write(f"REMARK   {title}\n")
        fh.write("REMARK   Generated by pychap (a Python reimplementation of CHAP's core\n")
        fh.write("REMARK   analysis); B-factor column encodes a pathway property for\n")
        fh.write("REMARK   visualisation (e.g. in VMD, 'colour by Beta').\n")

        for i in range(n_atoms):
            serial = (i + 1) % 100000
            name = str(atom_names[i])[:4]
            # PDB atom name alignment convention: 1-2 char element names
            # are placed starting at column 2 of the 4-char field (i.e.
            # padded with one leading space), 4-char names fill the field.
            if len(name) < 4:
                name_field = f" {name:<3s}"
            else:
                name_field = name

            resname = str(resnames[i])[:3].rjust(3)
            resid = int(resids[i]) % 10000
            x, y, z = positions[i]
            occ = float(occupancies[i])
            temp = float(b_factors[i])
            elem = str(elements[i])[:2].rjust(2)

            line = (
                f"ATOM  {serial:5d} {name_field:<4s} {resname:>3s} {chain:1s}{resid:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}{occ:6.2f}{temp:6.2f}          {elem:>2s}\n"
            )
            fh.write(line)

        fh.write("END\n")


def _guess_element(atom_name: str) -> str:
    """Fall back to pychap.elements' name-based element guess so the
    exported PDB has sensible element symbols even without explicit
    element information."""
    from .elements import guess_element_from_name

    return guess_element_from_name(atom_name)
